[workspace]
resolver = "2"
members = ["site-builder"]

[workspace.package]
version = "2.4.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
license = "Apache-2.0"

[profile.test]
opt-level = 1
