name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  pr-title:
    runs-on: ubuntu-latest
    name: Check PR title format
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  editorconfig:
    runs-on: "ubuntu-22.04"
    name: Check editorconfig
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: pip install editorconfig-checker=="2.7.3"
      - run: ec

  typos:
    runs-on: ubuntu-latest
    name: Check spelling
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: crate-ci/typos@392b78fe18a52790c53f42456e46124f77346842 # v1.34.0

  license-headers:
    runs-on: ubuntu-latest
    name: Check license headers
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # TODO: Consider repointing this to the upstream version again when https://github.com/notken12/licensesnip/pull/10 is merged.
      - run: cargo install --git https://github.com/wbbradley/licensesnip --rev a1037505417d06a3 licensesnip
      - run: licensesnip check

  prettier-portal:
    runs-on: ubuntu-latest
    name: Check portal formatting
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      - name: Check formatting
        working-directory: portal
        run: |
          bun install
          bunx prettier --check --editorconfig "**/*.ts"

  check-all:
    name: Check if all lint jobs succeeded
    if: always()
    needs:
      - pr-title
      - editorconfig
      - typos
      - license-headers
      - prettier-portal
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all needed jobs succeeded
      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
